const data = {
  products: [
    {
      _id: "1",
      name: "Silicone Strap For Apple Watch Band 44mm 40mm 45mm 41mm 49mm 42mm 38mm 44 45 mm bracelet iwatch series 7 se 3 4 5 6 8 Ultra band",
      category: "Shirts",
      image: "/images/watch.webp",
      price: 80.0,
      offer: 50.0,
      disPrice: 60,
      initialStock: 1000,
      countInStock: 500,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      Promotag: "buy 3 to get addition 10% off",
      isFreeshipping: true,
    },
    {
      _id: "2",
      name: "Silicone Strap For Apple Watch Band 44mm 40mm 45mm 41mm 49mm 42mm 38mm 44 45 mm bracelet iwatch series 7 se 3 4 5 6 8 Ultra band",
      category: "Shirts",
      image: "/images/watch.webp",
      price: 80.0,
      offer: 50.0,
      disPrice: 60,
      initialStock: 1000,
      countInStock: 500,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      Promotag: "buy 3 to get addition 10% off",
      isFreeshipping: true,
    },
    {
      _id: "3",
      name: "Silicone Strap For Apple Watch Band 44mm 40mm 45mm 41mm 49mm 42mm 38mm 44 45 mm bracelet iwatch series 7 se 3 4 5 6 8 Ultra band",
      category: "Shirts",
      image: "/images/watch.webp",
      price: 80.0,
      offer: 50.0,
      disPrice: 60,
      initialStock: 1000,
      countInStock: 500,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      Promotag: "buy 3 to get addition 10% off",
      isFreeshipping: true,
    },
    {
      _id: "4",
      name: "Silicone Strap For Apple Watch Band 44mm 40mm 45mm 41mm 49mm 42mm 38mm 44 45 mm bracelet iwatch series 7 se 3 4 5 6 8 Ultra band",
      category: "Shirts",
      image: "/images/watch.webp",
      price: 80.0,
      offer: 50.0,
      disPrice: 60,
      initialStock: 1000,
      countInStock: 500,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      Promotag: "buy 3 to get addition 10% off",
      isFreeshipping: true,
    },
    {
      _id: "5",
      name: "Silicone Strap For Apple Watch Band 44mm 40mm 45mm 41mm 49mm 42mm 38mm 44 45 mm bracelet iwatch series 7 se 3 4 5 6 8 Ultra band",
      category: "Shirts",
      image: "/images/watch.webp",
      price: 80.0,
      offer: 50.0,
      disPrice: 60,
      initialStock: 1000,
      countInStock: 500,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      Promotag: "buy 3 to get addition 10% off",
      isFreeshipping: true,
    },
    {
      _id: "6",
      name: "Silicone Strap For Apple Watch Band 44mm 40mm 45mm 41mm 49mm 42mm 38mm 44 45 mm bracelet iwatch series 7 se 3 4 5 6 8 Ultra band",
      category: "Shirts",
      image: "/images/watch.webp",
      price: 80.0,
      offer: 50.0,
      disPrice: 60,
      initialStock: 1000,
      countInStock: 500,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      Promotag: "buy 3 to get addition 10% off",
      isFreeshipping: true,
    },
    {
      _id: "7",
      name: "Silicone Strap For Apple Watch Band 44mm 40mm 45mm 41mm 49mm 42mm 38mm 44 45 mm bracelet iwatch series 7 se 3 4 5 6 8 Ultra band",
      category: "Shirts",
      image: "/images/watch.webp",
      price: 80.0,
      offer: 50.0,
      disPrice: 60,
      initialStock: 1000,
      countInStock: 500,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      Promotag: "buy 3 to get addition 10% off",
      isFreeshipping: true,
    },
    {
      _id: "8",
      name: "Silicone Strap For Apple Watch Band 44mm 40mm 45mm 41mm 49mm 42mm 38mm 44 45 mm bracelet iwatch series 7 se 3 4 5 6 8 Ultra band",
      category: "Shirts",
      image: "/images/watch.webp",
      price: 80.0,
      offer: 50.0,
      disPrice: 60,
      initialStock: 1000,
      countInStock: 500,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      Promotag: "buy 3 to get addition 10% off",
      isFreeshipping: true,
    },
    {
      _id: "9",
      name: "Silicone Strap For Apple Watch Band 44mm 40mm 45mm 41mm 49mm 42mm 38mm 44 45 mm bracelet iwatch series 7 se 3 4 5 6 8 Ultra band",
      category: "Shirts",
      image: "/images/watch.webp",
      price: 80.0,
      offer: 50.0,
      disPrice: 60,
      initialStock: 1000,
      countInStock: 500,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      Promotag: "buy 3 to get addition 10% off",
      isFreeshipping: true,
    },
    {
      _id: "10",
      name: "Silicone Strap For Apple Watch",
      category: "Shirts",
      image: "/images/watch.webp",
      price: 80.0,
      offer: 50.0,
      disPrice: 60,
      initialStock: 1000,
      countInStock: 500,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      Promotag: "buy 3 to get addition 10% off",
      isFreeshipping: true,
    },
    {
      _id: "11",
      name: "Silicone Strap For Apple Watch",
      category: "Shirts",
      image: "/images/watch.webp",
      price: 80.0,
      offer: 50.0,
      disPrice: 60,
      initialStock: 1000,
      countInStock: 500,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      Promotag: "buy 3 to get addition 10% off",
      isFreeshipping: true,
    },
    {
      _id: "12",
      name: "Silicone Strap For Apple Watch",
      category: "Shirts",
      image: "/images/watch.webp",
      price: 80.0,
      offer: 50.0,
      disPrice: 60,
      initialStock: 1000,
      countInStock: 500,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      Promotag: "buy 3 to get addition 10% off",
      isFreeshipping: true,
    },
    {
      _id: "13",
      name: "Silicone Strap For Apple Watch",
      category: "Shirts",
      image: "/images/watch.webp",
      price: 80.0,
      offer: 50.0,
      disPrice: 60,
      initialStock: 1000,
      countInStock: 500,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      Promotag: "buy 3 to get addition 10% off",
      isFreeshipping: true,
    },
    {
      _id: "14",
      name: "Silicone Strap For Apple Watch",
      category: "Shirts",
      image: "/images/watch.webp",
      price: 80.0,
      offer: 50.0,
      disPrice: 60,
      initialStock: 1000,
      countInStock: 500,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      Promotag: "buy 3 to get addition 10% off",
      isFreeshipping: true,
    },
    {
      _id: "15",
      name: "Silicone Strap For Apple Watch",
      category: "Shirts",
      image: "/images/watch.webp",
      price: 80.0,
      offer: 50.0,
      disPrice: 60,
      initialStock: 1000,
      countInStock: 500,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
      Promotag: "buy 3 to get addition 10% off",
      isFreeshipping: true,
    },
  ],
};

export default data;
